# -*- coding: utf-8 -*-
{
    'name': 'LBS Dashboard',
    'description': 'Odoo Dashboard',
    'author': 'LBS Company',
    'license': 'OPL-1',
    'category': 'Tools',
    'version': '15.0.1',
    'depends': ['base', 'web', 'base_setup', 'bus'],
    'data': ['security/ir.model.access.csv', 'security/ks_security_groups.xml', 'data/ks_default_data.xml',
             'views/ks_dashboard_ninja_view.xml', 'views/ks_dashboard_ninja_item_view.xml',
             'views/ks_dashboard_action.xml', 'views/ks_import_dashboard_view.xml',
             'wizard/ks_create_dashboard_wiz_view.xml', 'wizard/ks_duplicate_dashboard_wiz_view.xml'],
    'assets': {'web.assets_backend': ['lbs_dashboard/static/src/css/lbs_dashboard.scss',
                                      'lbs_dashboard/static/src/css/ks_dashboard_ninja_item.css',
                                      'lbs_dashboard/static/src/css/ks_icon_container_modal.css',
                                      'lbs_dashboard/static/src/css/dashboard_item_theme.css',
                                      'lbs_dashboard/static/src/css/ks_dn_filter.css',
                                      'lbs_dashboard/static/src/css/ks_toggle_icon.css',
                                      'lbs_dashboard/static/src/css/ks_dashboard_options.css',
                                      'lbs_dashboard/static/src/js/ks_global_functions.js',
                                      'lbs_dashboard/static/src/js/lbs_dashboard.js',
                                      'lbs_dashboard/static/src/js/ks_to_do_dashboard.js',
                                      'lbs_dashboard/static/src/js/ks_filter_props.js',
                                      'lbs_dashboard/static/src/js/ks_color_picker.js',
                                      'lbs_dashboard/static/src/js/ks_dashboard_ninja_item_preview.js',
                                      'lbs_dashboard/static/src/js/ks_image_basic_widget.js',
                                      'lbs_dashboard/static/src/js/dashboard_item_theme.js',
                                      'lbs_dashboard/static/src/js/ks_widget_toggle.js',
                                      'lbs_dashboard/static/src/js/ks_import_dashboard.js',
                                      'lbs_dashboard/static/src/js/ks_domain_fix.js',
                                      'lbs_dashboard/static/src/js/ks_quick_edit_view.js',
                                      'lbs_dashboard/static/src/js/ks_dashboard_ninja_kpi_preview.js',
                                      'lbs_dashboard/static/src/js/ks_date_picker.js',
                                      'lbs_dashboard/static/lib/css/gridstack.min.css',
                                      'lbs_dashboard/static/lib/js/gridstack-h5.js',
                                      'lbs_dashboard/static/lib/js/Chart.bundle.min.js',
                                      'lbs_dashboard/static/src/css/ks_dashboard_ninja_pro.css',
                                      'lbs_dashboard/static/src/css/ks_to_do_item.css',
                                      'lbs_dashboard/static/src/js/ks_dashboard_ninja_graph_preview.js',
                                      'lbs_dashboard/static/src/js/ks_dashboard_ninja_list_view_preview.js',
                                      'lbs_dashboard/static/src/js/ks_to_do_preview.js'],
               'web.assets_qweb': ['lbs_dashboard/static/src/xml/**/*']},
    'uninstall_hook': 'uninstall_hook',
}
